CREATE OR REPLACE FUNCTION weekdays(DATE, DATE) RETURNS INTEGER AS
$$
  SELECT COUNT(days)::INTEGER
  FROM generate_series(LEAST($1, $2), GREATEST($1, $2), '1 day') AS days
  WHERE EXTRACT(DOW FROM days) NOT IN (0, 6);
$$
LANGUAGE SQL;